### ISSUE TITLE
Failed to parse the snapshot generated using Chrome Version 65.0.3325.162 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by masterkidan** [SrTobi/v8-heapsnapshot#1]
Got the following error: 
Error: Heapsnapshot format changed! Please report to https://github.com/SrTobi/v8-heapsnapshot/issues
    at t (/home/masterkidan/Playground/NodeJS/HeapParser/dist/bundle.js:10:37886)
    at /home/masterkidan/Playground/NodeJS/HeapParser/dist/bundle.js:10:38335
    at /home/masterkidan/Playground/NodeJS/HeapParser/dist/bundle.js:10:38629
    at Generator.next (<anonymous>)
    at o (/home/masterkidan/Playground/NodeJS/HeapParser/dist/bundle.js:10:35523)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by masterkidan** [comment]
![screenshot from 2018-03-20 18-49-40](https://user-images.githubusercontent.com/942002/37691493-b1c1ceec-2c6f-11e8-9fd4-2bb4ab300a39.png)

See above screenshot for the diff

**Comment by SrTobi** [comment]
I fixed it. Update the package and it should work. Thank you for reporting.

May I ask you how you got the package to run in the first place? I saw that there was still debugging code not commented out and that should have been run everytime the package was loaded...

**Comment by masterkidan** [comment]
I commented out the code in the outputted js file :)

**Comment by SrTobi** [comment]
ok good. I thought there was a different version on npm than on git which would have been curious to say the least
